version: '2'
services:

  devcontainer:
    build:
      context: .
      args:
        DBT_VERSION: 1.0.0
    volumes:
      - .:/workspace
    ports:
      - 8083:8080

  postgres:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
