name: Continuous Integration Tests

on:
  pull_request:
    branches: [ main ]
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true  

jobs:

  ci_test:
    name: Postgres Jaffle Shop DataVault CI
    timeout-minutes: 5
    runs-on: ubuntu-latest
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    container:
      image: ghcr.io/dwh-course-examples/dbt-datavault-postgres:ci
    steps:
      - uses: actions/checkout@v3
      - run: dbt --version
      - run: dbt debug --target ci
      - run: dbt deps --target ci
      - run: dbt build --target ci
